site_name: 浩哈哈哈哈
theme: 
  name: material
  icon:
    logo: material/noodles
  favicon: https://alg.haohaha.cn/image/favicon.png
  palette:
    - scheme: slate # 夜间模式
      primary: black # deep purple
      accent: light green # deep orange
      toggle:
        icon: material/brightness-4
        name: 切换至日间模式
    - scheme: default # 日间模式
      primary: white # deep purple # 上方的
      accent: deep orange # deep orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/brightness-7 # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.expand # 展开
    # navigation.prune # 折叠
    - search.suggest
    - search.highlight
    - content.code.copy
    - Instant Loading
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    # Anchor tracking
    - navigation.tracking
  language: zh

edit_uri: edit/main/docs

nav:
  - Home: https://haohaha.cn
  - Be_Rational: http://cs.haohaha.cn
  - Chat_Polka: http://chat.haohaha.cn 
  - Algorithm: 
    - Home: index.md
    - 做点儿题: 
      - hz333/index.md
    - 代码随想录: 
      - 第3章 数组:
        - 3-1 二分查找: CodeThinker/3/2022-06-07_3-1_二分查找.md
        - 3-2 移除元素: CodeThinker/3/2022-06-08_3-2_移除元素.md
        - 3-3 长度最小子数组: CodeThinker/3/2022-06-09_3-3_长度最小子数组.md
        - 3-4 循环不变量: CodeThinker/3/2022-06-10_3-4_循环不变量.md
      - 第4章 链表:
        - 4-1 删除节点: CodeThinker/4/2022-06-13_4-1_删除节点.md
        - 4-2 设计链表: CodeThinker/4/2022-06-27_4-2_设计链表.md
        - 4-3 反转链表: CodeThinker/4/2022-06-28_4-3_反转链表.md
        - 4-4 删除倒数第n个节点: CodeThinker/4/2022-07-01_4-4_删除倒数第n个节点.md
        - 4-5 环形链表: CodeThinker/4/2022-07-12_4-5_环形链表.md
      - 第5章 哈希表:
        - 5-1 有效的字母异位词: CodeThinker/5/2022-08-07_5-1.md
        - 5-2 两个数组的交集: CodeThinker/5/2022-10-06_5-2.md
        - 5-3 两数之和: CodeThinker/5/2022-10-09_5-3.md
        - 5-4 四数相加: CodeThinker/5/2022-11-23_5-4.md
        - 5-5 三数之和: CodeThinker/5/2022-11-24_5-5.md
      - 第7章 栈与队列:
        - 7-4 有效的括号: CodeThinker/7/2023-05-05_7-4.md
        - 7-5 删除字符串中的所有相邻重复项: CodeThinker/7/2023-05-07_7-5.md
        - 7-6 逆波兰表达式: CodeThinker/7/2023-05-01_7-6.md
    - 以前练的题:
      - Uva1585,Score: old/2021-08-03_Uva1585,Score/2021-08-03_Uva1585,Score.md
      - Uva272,Tex_Quotes: old/2021-08-04_Uva272,Tex_Quotes/2021-08-04_Uva272,Tex_Quotes.md
      - Uva1583,Digit_Generator: old/2021-08-11_Uva1583,Digit_Generator/2021-08-11_Uva1583,Digit_Generator.md
      - Uva1584,Circular_Sequence: old/2021-08-12_Uva1584,Circular_Sequence/2021-08-12_Uva1584,Circular_Sequence.md
      - Uva1586,Molar_Mass: old/2021-08-14_Uva1586,Molar_Mass/2021-08-14_Uva1586,Molar_Mass.md
      - Uva1225,Digit_Counting: old/2021-08-18_Uva1225,Digit_Counting/2021-08-18_Uva1225,Digit_Counting.md
      - Merge-Sort: old/2021-10-28_Merge-Sort/2021-10-28_Merge-Sort.md
      - Inorder-Traversal: old/2021-10-29_Inorder-Traversal/2021-10-29_Inorder-Traversal.md
      - Binary-Search: old/2021-10-31_Binary-Search/2021-10-31_Binary-Search.md

extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
  - mkdocs/extra_admonition.css # 自定义admonition

markdown_extensions:
    # Admonitions
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    # Icons, Emojis
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    # Formatting
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    # Diagrams
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tasklist:
        custom_checkbox: true

extra:
  homepage: http://haohaha.cn
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/1436476753
      name: Bilibili | 浩哈哈哈哈 # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/Haohahahaha
      name: GitHub | Haohahahaha
    - icon: simple/githubactions
      link: https://github.com/Haohahahaha/alg/actions
      name: GitHub Actions
## [bottom-left corner]
copyright: 
  <a href="https://beian.miit.gov.cn/" target="_blank">冀ICP备2024078994号</a><br/>
  <a href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=13020302001386" target="_blank">冀公网安备13020302001386号</a><br/>
  Copyright &copy; 2022-现在 浩哈哈哈哈_ # 左下角的版权声明
